src/building/urls.py
from django.urls import path
from building.views import (
    BuildingCreateView,
    BuildingDeleteView,
    BuildingDetailView,
    BuildingExport,
    BuildingListView,
    BuildingPresenceStatisticView,
    BuildingSearchView,
    BuildingUpdateView,
    OfficePresenceStatisticsExport,
    OfficePresenceStatisticsListView,
    BuildingDocumentCreateView,
    BuildingDocumentRemoveView,
)


urlpatterns = [
    path(
        "office/presence/statistics",
        OfficePresenceStatisticsListView.as_view(),
        name="office_presence_statistics_list",
    ),
    path(
        "office/presence/statistics/export",
        OfficePresenceStatisticsExport.as_view(),
        name="office_presence_statistics_export",
    ),
    path("building/", BuildingListView.as_view(), name="building_list"),
    path("building/<int:pk>", BuildingDetailView.as_view(), name="building_details"),
    path("building/create", BuildingCreateView.as_view(), name="building_creation"),
    path(
        "building/update/<int:pk>", BuildingUpdateView.as_view(), name="building_update"
    ),
    path(
        "building/delete/<int:pk>", BuildingDeleteView.as_view(), name="building_delete"
    ),
    path("building/search/", BuildingSearchView.as_view(), name="building_search"),
    path("building/export/", BuildingExport.as_view(), name="building_export"),
    path(
        "building/<int:pk>/presence/statistic",
        BuildingPresenceStatisticView.as_view(),
        name="building_presence_statistic_list",
    ),
    path(
        "building/update/upload/<int:pk>",
        BuildingDocumentCreateView.as_view(),
        name="building_document_creation",
    ),
    path(
        "building/update/<int:pk>/removedocument/<int:lpk>",
        BuildingDocumentRemoveView.as_view(),
        name="building_remove_document",
    ),
]

src/core/urls.py
from django.urls import include, path
from service.views.index import IndexView
from service import urls as service_urls
from hardware import urls as hardware_urls
from scim import urls as scim_urls
from restapi import urls as restapi_urls
from gql import urls as gql_urls
from admin import urls as admin_urls
from application import urls as application_urls
from building import urls as building_urls
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import (
    AuthorizationView,
    TokenView,
    RevokeTokenView,
    IntrospectTokenView,
)


# swagger doc: https://appliku.com/post/django-rest-framework-swagger-and-typescript-api-c#swagger-documentation
# and https://pypi.org/project/drf-yasg/#installation

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include(service_urls)),
    path("", include(scim_urls)),
    path("", include(hardware_urls)),
    path("", include(restapi_urls)),
    path("", include(gql_urls)),
    path("", include(admin_urls)),
    path("", include(application_urls)),
    path("", include(building_urls)),
    path("accounts/", include("allauth.urls")),
    path("hc/", include("health_check.urls")),
    path("oauth/authorize/", AuthorizationView.as_view(), name="authorize"),
    path("oauth/token/", TokenView.as_view(), name="token"),
    path("oauth/revoke_token/", RevokeTokenView.as_view(), name="revoke-token"),
    path("oauth/introspect/", IntrospectTokenView.as_view(), name="introspect"),
]

if settings.OIDC_ACTIVATED:
    urlpatterns.append(
        path("oidc/", include("mozilla_django_oidc.urls")),
    )

if not settings.USE_AWS_S3_FOR_FILES:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gql/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from gql.schema import schema

urlpatterns = [
    path("gql/", GraphQLView.as_view(graphiql=True, schema=schema), name="grapheql"),
]

src/building/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import default_storage
from service.storages import AWSPrivateMediaStorage
import os
from service.models import Company, ContractDocument


class Country(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    country_code = models.CharField(max_length=2, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_country_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("country")
        verbose_name_plural = _("countries")
        ordering = ["id"]
        permissions = [
            ("export_country", "Can export country"),
        ]

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=3, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_currency_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("currency")
        verbose_name_plural = _("currencies")
        ordering = ["id"]
        permissions = [
            ("export_currency", "Can export currency"),
        ]

    def __str__(self):
        return self.name


class BuildingType(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_building_type_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("building type")
        verbose_name_plural = _("building types")
        ordering = ["id"]
        permissions = [
            ("export_building_type", "Can export building type"),
        ]

    def __str__(self):
        return self.name


class BuildingSize(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_building_size_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("building size")
        verbose_name_plural = _("building size")
        ordering = ["id"]
        permissions = [
            ("export_building_size", "Can export building size"),
        ]

    def __str__(self):
        return self.name


class Building(models.Model):
    STATUS = (
        ("active", "Active"),
        ("suspended", "Suspended"),
        ("decommissioned", "Decommissioned"),
    )

    def get_upload_path(instance, filename):
        name, ext = os.path.splitext(filename)
        return os.path.join("building", str(instance.id), name + ext)

    def get_storage():
        storage = default_storage
        if settings.USE_AWS_S3_FOR_FILES:
            storage = AWSPrivateMediaStorage()
        return storage

    name = models.CharField(max_length=255, blank=False, null=False)
    target_presence = models.IntegerField(blank=True, null=True)

    building_manager = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="FK_building_manager_user_id"
    )
    it_support = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="FK_building_it_support_user_id",
    )
    general_manager = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="FK_building_general_manager_user_id",
    )
    culture_embassador = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="FK_building_culture_ambassador_user_id",
    )
    people_director = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="FK_building_people_director_user_id",
    )
    people_partner = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="FK_building_people_partner_user_id",
    )
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    company = models.ForeignKey(
        Company, on_delete=models.SET_NULL, blank=True, null=True
    )

    capacity = models.IntegerField(null=True, blank=True)
    square_meters = models.FloatField(null=True, blank=True)
    document = models.ManyToManyField(ContractDocument, blank=True)
    reception = models.BooleanField(default=False, null=False, blank=False)
    type = models.ForeignKey(
        BuildingType, on_delete=models.SET_NULL, blank=True, null=True
    )
    phone_number = models.CharField(null=True, blank=True, max_length=30)
    size = models.ForeignKey(
        BuildingSize, on_delete=models.SET_NULL, blank=True, null=True
    )
    renting = models.BooleanField(default=False, null=False, blank=False)
    start_rending_date = models.DateTimeField(null=True, blank=True)
    cost_per_month = models.FloatField(null=True, blank=True)
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, blank=True, null=True
    )
    banner = models.ImageField(
        upload_to=get_upload_path, null=True, blank=True, storage=get_storage()
    )
    status = models.CharField(max_length=30, choices=STATUS, default="active")
    meeting_rom_quantity = models.IntegerField(null=True, blank=True)
    phonebooth_quantity = models.IntegerField(null=True, blank=True)
    amphitheater_quantity = models.IntegerField(null=True, blank=True)

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_building_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("building")
        verbose_name_plural = _("buildings")
        ordering = ["id"]
        permissions = [
            ("export_building", "Can export building"),
            ("add_document", "Can add document to building"),
            ("delete_document", "Can delete document from building"),
            ("view_document", "Can view document from building"),
        ]

    def __str__(self):
        return self.name


class PublicIP(models.Model):
    ip = models.GenericIPAddressField(blank=False, null=True, unique=True)
    building = models.ForeignKey(
        Building,
        on_delete=models.SET_NULL,
        related_name="public_ips",
        blank=True,
        null=True,
    )
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_public_ip_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("public IP")
        verbose_name_plural = _("Public IPs")
        ordering = ["id"]
        permissions = [
            ("export_public_ip", "Can export public IP"),
        ]

    def __str__(self):
        return self.ip


class Controller(models.Model):
    TYPE = (
        ("entrance", "Entrance"),
        ("exit", "Exit"),
        ("storage_room", "Storage room"),
        ("rack_room", "Rack room"),
        ("it_storage", "IT Storage room"),
    )
    name = models.CharField(max_length=255, blank=False, null=False)
    external_id = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=30, choices=TYPE, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_controller_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("controller")
        verbose_name_plural = _("controllers")
        ordering = ["id"]
        permissions = [
            ("export_controller", "Can export controller"),
        ]

    def __str__(self):
        return self.name


class AccessControlRecord(models.Model):
    source_id = models.IntegerField(blank=False, null=False, unique=True)
    building = models.ForeignKey(
        Building,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=False,
    )
    date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_access_control_user_id",
    )
    card = models.CharField(max_length=255, blank=True, null=True)
    controller = models.ForeignKey(
        Controller, on_delete=models.SET_NULL, blank=True, null=True
    )
    user_type = models.CharField(max_length=255, blank=True, null=True)

src/building/forms.py
from django import forms
from service.models import ContractDocument


class UploadBuildingDocumentFrom(forms.ModelForm):
    class Meta:
        model = ContractDocument
        fields = ["file"]

src/templates/building/elements/details_banner.html
{% load static %}
{% load service_custom_tags %}

<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="user-profile-header-banner">
        {% if instance_object.banner %}
          <img src="{{ instance_object.banner.url }}" alt="Banner image" class="rounded-top" />
        {% else %}
          <img src="{% static 'img/banner.png' %}" alt="Banner image" class="rounded-top" />
        {% endif %}
      </div>
      <div class="user-profile-header d-flex flex-column flex-sm-row text-sm-start text-center mb-4">
        <div class="flex-grow-1 mt-3 mt-sm-5">
          <div class="d-flex align-items-md-end align-items-sm-start align-items-center justify-content-md-between justify-content-start mx-4 flex-md-row flex-column gap-4">
            <div class="user-profile-info">
              <h4>{{ instance_object.name }}</h4>
              <ul class="list-inline mb-0 d-flex align-items-center flex-wrap justify-content-sm-start justify-content-center gap-2">
                <li class="list-inline-item fw-semibold">
                  {% include 'generic/elements/status.html' %}
                </li>
              </ul>
            </div>

            {% if perms.building.change_building %}
              <a href='{% url update_url pk=instance_object.id %}' class="btn btn-primary text-nowrap"><i class="bx bx-pencil"></i> Edit</a>
            {% else %}
              <a href="" class="btn btn-primary text-nowrap disabled"><i class="bx bx-pencil"></i> Edit</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/building/elements/nav_building_document.html
<!-- tab main -->
<div class="tab-pane fade {{ tab_active_value }}" id="navs-pills-top-document" role="tabpanel">
  <div class="card mb-4">
    <h5 class="card-header">Documents</h5>
    {% if perms.building.add_document %}
    <div class="card-body">
        
      <div class="button-wrapper">
        <form action="{% url 'building_document_creation' pk=instance_object.id %}" enctype="multipart/form-data" method="POST" novalidate>
            {% csrf_token %}
        <div class="input-group">

            <input class="form-control" type="file" id="id_file" name="file"/>
            <button type="submit" class="btn btn-outline-primary">Upload</button>
        </form>


      </div>
    </div>
      
    </div>
    <hr class="my-0" />
    {% endif %}

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">Action</th>
              <th scope="col">Filename</th>
            </tr>
          </thead>
          <tbody>
            {% for object in instance_object.document.all %}

            <tr>
              {% with placeholder_unlink_url='building_remove_document' source_id=instance_object.id %}
              {% include 'generic/views/create_update/elements/td_action_document.html' %}
              {% endwith %}
              <td>{{ object.name }}</td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

src/templates/building/elements/nav_chart.html
<!-- tab -->
{% load building_custom_tags %}
{% load static %}

{% get_pesence_target building_pk as target_presence %}

<div class="tab-pane fade show" id="navs-pills-top-chart" role="tabpanel">
  <div class="card mb-4">
    <div class="card-body">
      <div class="row"></div>
      <div>
        <figure class="highcharts-figure">
          <div id="presence_per_day_per_type"></div>
        </figure>
        {{ instance_object|json_script:'chart1' }}{{ target_presence|json_script:'target_presence' }}
      </div>
    </div>
  </div>
</div>

src/templates/building/elements/nav_main.html
<!-- tab -->
<div class="tab-pane fade show active" id="navs-pills-top-main" role="tabpanel">
  <div class="card mb-4">
    <h5 class="card-header">Main</h5>
    <div class="card-body">
      <div class="row">
        <div class="table-responsive">
          <table class="table" id="datatable">
            <thead>
              <tr>
                <th scope="col">Year</th>
                <th scope="col">Week</th>
                <th scope="col">Date</th>
                <th scope="col">Type</th>
                <th scope="col">Count of entry</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
              {% for object in instance_object %}
                <tr>
                  <td>{{ object.year }}</td>
                  <td>{{ object.week_num }}</td>
                  <td>{{ object.date_value|date:'d/m/Y' }}</td>
                  <td>{{ object.type }}</td>
                  <td>{{ object.count_entry }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/building/elements/td_action_button.html
{% load service_custom_tags %}

<td>
    <div class="btn-group">
    <a class="btn btn-primary btn-sm btn-icon" type="button" href="{% url details_url pk=object.id %}"><i class='bx bx-info-circle'></i></a>
    {% if perms.building.view_accesscontrolrecord %}
    <a class="btn btn-primary btn-sm btn-icon" type="button" href="{% url 'building_presence_statistic_list' pk=object.id %}"><i class='bx bx-stats'></i></a>
    {% endif %}
    <button type="button" class="btn btn-sm btn-primary btn-icon dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="visually-hidden">Action</span>
    </button>
    
    <ul class="dropdown-menu">

        <li><a class="dropdown-item {% if not perms.building.change_building %}disabled{% endif %}" href="{% url update_url pk=object.id %}"><i class="bx bx-pencil"></i> Edit</a></li>
        <li><a class="dropdown-item {% if not perms.building.delete_building %}disabled{% endif %}" href="{% url delete_url pk=object.id %}"><i class="bx bx-trash-alt"></i> Delete</a></li>
        
        <li><a class="dropdown-item {% if not perms.building.export_access_control_record %}disabled{% endif %}" href="{% url 'office_presence_statistics_list' %}?office={{object.name}}&year={% now 'Y' %}"><i class='bx bx-stats'></i>Raw SQL Presence</a></li>
        <li><a class="dropdown-item {% if not perms.building.export_access_control_record %}disabled{% endif %}" href="{% url 'office_presence_statistics_export' %}?office={{object.name}}&year={% now 'Y' %}"><i class='bx bx-cloud-download' ></i>Raw SQL Extract</a></li>

    </ul>

    </div>
</td>