src/core/urls.py
from django.urls import include, path
from service.views.index import IndexView
from service import urls as service_urls
from hardware import urls as hardware_urls
from scim import urls as scim_urls
from restapi import urls as restapi_urls
from gql import urls as gql_urls
from admin import urls as admin_urls
from application import urls as application_urls
from building import urls as building_urls
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import (
    AuthorizationView,
    TokenView,
    RevokeTokenView,
    IntrospectTokenView,
)


# swagger doc: https://appliku.com/post/django-rest-framework-swagger-and-typescript-api-c#swagger-documentation
# and https://pypi.org/project/drf-yasg/#installation

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include(service_urls)),
    path("", include(scim_urls)),
    path("", include(hardware_urls)),
    path("", include(restapi_urls)),
    path("", include(gql_urls)),
    path("", include(admin_urls)),
    path("", include(application_urls)),
    path("", include(building_urls)),
    path("accounts/", include("allauth.urls")),
    path("hc/", include("health_check.urls")),
    path("oauth/authorize/", AuthorizationView.as_view(), name="authorize"),
    path("oauth/token/", TokenView.as_view(), name="token"),
    path("oauth/revoke_token/", RevokeTokenView.as_view(), name="revoke-token"),
    path("oauth/introspect/", IntrospectTokenView.as_view(), name="introspect"),
]

if settings.OIDC_ACTIVATED:
    urlpatterns.append(
        path("oidc/", include("mozilla_django_oidc.urls")),
    )

if not settings.USE_AWS_S3_FOR_FILES:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gql/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from gql.schema import schema

urlpatterns = [
    path("gql/", GraphQLView.as_view(graphiql=True, schema=schema), name="grapheql"),
]

src/hardware/models.py
from django.db import models
from django.conf import settings
from service.storages import AWSPrivateMediaStorage
from service.models import Provider, Pricing, Contract, Department, SubDepartment, Title
from django.core.files.storage import default_storage
from django.utils.translation import gettext_lazy as _
import os


class HardwareCategory(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_hardware_category_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("hardware category")
        verbose_name_plural = _("hardware categories")
        ordering = ["id"]
        permissions = [
            ("export_hardware_catagory", "Can export hardware catagory"),
        ]

    def __str__(self):
        return self.name


class Hardware(models.Model):
    STATUS = (
        ("active", "Active"),
        ("decommission", "Decommission"),
    )

    def get_upload_path(instance, filename):
        name, ext = os.path.splitext(filename)
        return os.path.join("hardwares", str(instance.id), name + ext)

    def get_storage():
        storage = default_storage
        if settings.USE_AWS_S3_FOR_FILES:
            storage = AWSPrivateMediaStorage()
        return storage

    name = models.CharField(max_length=255, blank=False, null=True)
    description = models.CharField(max_length=5000, blank=False, null=False)
    provider = models.ForeignKey(
        Provider, on_delete=models.CASCADE, blank=True, null=True, auto_created=False
    )
    status = models.CharField(max_length=30, choices=STATUS, default="active")
    category = models.ForeignKey(
        HardwareCategory,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        auto_created=False,
    )
    model_name = models.CharField(max_length=255, blank=True, null=True)
    model_number = models.CharField(max_length=255, blank=True, null=True)
    contract = models.ManyToManyField(Contract, blank=True)
    icon = models.ImageField(
        upload_to=get_upload_path, null=True, blank=True, storage=get_storage()
    )
    pricing = models.ManyToManyField(Pricing, blank=True)
    support_url = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_hardware_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("hardware")
        verbose_name_plural = _("hardwares")
        ordering = ["id"]
        permissions = [
            ("export_hardware", "Can export hardware"),
        ]

    def __str__(self):
        return self.name


class RuleMapping(models.Model):
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )
    subdepartment = models.ForeignKey(
        SubDepartment,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )
    title = models.ForeignKey(
        Title,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_rule_mapping_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        unique_together = ("department", "subdepartment", "title")
        verbose_name = _("rule mapping")
        verbose_name_plural = _("rules mapping")
        ordering = ["id"]
        permissions = [
            ("export_rule_mapping", "Can export rule mapping"),
        ]

    def __str__(self):
        return str(f"{self.department}/{self.subdepartment}/{self.title}")


class HardwareMapping(models.Model):
    rule = models.ForeignKey(
        RuleMapping,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )

    hardware = models.ManyToManyField(Hardware, blank=True)

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_hardware_mapping_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("hardware mapping")
        verbose_name_plural = _("hardware mapping")
        ordering = ["id"]
        permissions = [
            ("export_hardware_mapping", "Can export hardware mapping"),
        ]

    def __str__(self):
        return str(
            f"{self.rule.department}/{self.rule.subdepartment}/{self.rule.title}"
        )

src/service/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from service.manager import UserManager
from django.conf import settings
from service.storages import AWSPrivateMediaStorage
from django.core.files.storage import default_storage
import os
from django.core.mail import send_mail


class Configuration(models.Model):
    CATEGORY = (
        ("public", "Public"),
        ("social_provider", "Social provider"),
        ("private", "private"),
    )
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, blank=True, null=True)
    category = models.CharField(
        max_length=30, choices=CATEGORY, default="private", editable=True
    )
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    enabled = models.BooleanField(default=False, verbose_name=_("Enabled"))

    class Meta:
        verbose_name = _("configuration")
        verbose_name_plural = _("configurations")
        ordering = ["id"]
        permissions = [
            ("export_configuration", "Can export configuration"),
        ]

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_department_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("department")
        verbose_name_plural = _("departments")
        ordering = ["id"]
        permissions = [
            ("export_department", "Can export department"),
        ]

    def __str__(self):
        return self.name


class SubDepartment(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=False,
    )
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_subdepartment_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("sub-department")
        verbose_name_plural = _("sub-departments")
        ordering = ["id"]
        permissions = [
            ("export_subdepartment", "Can export sub-department"),
        ]

    def __str__(self):
        return self.name


class Title(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_title_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("title")
        verbose_name_plural = _("titles")
        ordering = ["id"]
        permissions = [
            ("export_title", "Can export title"),
        ]

    def __str__(self):
        return self.name


class ServiceCategory(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_service_category_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("service category")
        verbose_name_plural = _("service categories")
        ordering = ["id"]
        permissions = [
            ("export_service_catagory", "Can export service catagory"),
        ]

    def __str__(self):
        return self.name


class IdentityProvider(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    icon_url = models.CharField(max_length=255, blank=True, null=True)
    service_url = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_identity_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("identity provider")
        verbose_name_plural = _("identity providers")
        ordering = ["id"]
        permissions = [
            ("export_identity_provider", "Can export identity provider"),
        ]

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_contact_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")
        ordering = ["id"]
        permissions = [
            ("export_contact", "Can export contact"),
        ]

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    currency_preffered = models.CharField(max_length=3, blank=True, null=True)
    contact = models.ManyToManyField(Contact, blank=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("provider")
        verbose_name_plural = _("providers")
        ordering = ["id"]
        permissions = [
            ("export_provider", "Can export provider"),
        ]

    def __str__(self):
        return self.name


class Company(models.Model):
    TRADE_REGISTER = (
        ("public", "Public"),
        ("restricted_access", "Restricted Access"),
        (
            "restricted_access_registry",
            "Restricted Access (business registry except required to requested)",
        ),
    )

    name = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    invoice_email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    brand_name = models.CharField(max_length=255, blank=True, null=True)
    activity = models.CharField(max_length=255, blank=True, null=True)
    incorporation_date = models.DateTimeField(blank=True, null=True)
    share_capital = models.FloatField(blank=True, null=True)
    tax_id = models.CharField(max_length=255, blank=True, null=True)
    trade_register = models.CharField(
        max_length=255, choices=TRADE_REGISTER, editable=True, null=True, blank=True
    )
    shareholders = models.CharField(max_length=255, blank=True, null=True)

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_company_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("company")
        verbose_name_plural = _("companies")
        ordering = ["id"]
        permissions = [
            ("export_company", "Can export company"),
        ]

    def __str__(self):
        return self.name


class ContractDocument(models.Model):
    default_upload_folder = "contract"

    def set_upload_folder(self, folder_name):
        self._upload_folder = folder_name

    def get_upload_folder(self):
        return getattr(self, "_upload_folder", self.default_upload_folder)

    def get_upload_path(instance, filename):
        name, ext = os.path.splitext(filename)
        return os.path.join(instance.get_upload_folder(), str(instance.lpk), name + ext)

    def get_storage():
        storage = default_storage

src/templates/generic/elements/footer_button.html
<div class="buy-now">
    <a
      href="{% url 'service_creation' %}"
      target="_blank"
      class="btn btn-primary btn-buy-now"
      >Add service</a
    >
  </div>

src/templates/generic/elements/icon_placeholder.html
<i class="bx bx-radio-circle"></i>

src/templates/generic/elements/pagination.html
{% load static %}

<div class="demo-inline-spacing">
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

      {% if page_obj.has_previous %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page_obj.previous_page_number }}&query={{ request.GET.query }}"><i class="tf-icon bx bx-chevron-left"></i></a>
      </li>
      {% if page_obj.number > 3 %}
      <a class="page-link" href="?page=1">1</a>
      {% if page_obj.number > 4 %}
      <li class="page-item">
        <a class="page-link disabled">...</a>
      </li>
      {% endif %} {% endif %} {% endif %} {% for num in page_obj.paginator.page_range %} {% if page_obj.number == num %}
      <li class="page-item active">
        <a
          class="page-link"
          href="?page={{ num }}&query={{ request.GET.query }}">{{ num }}</a
        >
      </li>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ num }}&query={{ request.GET.query }}">{{ num }}</a>
      </li>
      {% endif %} {% endfor %} {% if page_obj.has_next %} {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
      <li class="page-item">
        <a class="page-link disabled">...</a>
      </li>
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page_obj.paginator.num_pages }}&query={{ request.GET.query }}">{{ page_obj.paginator.num_pages }}</a>
      </li>
      {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page_obj.paginator.num_pages }}&query={{ request.GET.query }}">{{ page_obj.paginator.num_pages }}</a>
      </li>
      {% endif %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page_obj.next_page_number }}&query={{ request.GET.query }}"><i class="tf-icon bx bx-chevron-right"></i></a>
      </li>

      {% endif %}
    </ul>
  </nav>
</div>

src/templates/generic/elements/service_link_form.html
{% load service_custom_tags %}

<form action='{% url placeholder_form_url pk=instance_object.id %}?tab={{link_name|lower}}' enctype="multipart/form-data" method="POST" novalidate class="needs-validation">
  {% csrf_token %}

  <div class="input-group">
    <select class="select form-control custom-select tom-select" id="id_relation_{{ link_name|lower }}" name="relation" required aria-label="Select a {{ link_name|lower }}" placeholder="Select a {{ link_name|lower }}">
      <option value="">Select {{ link_name|lower }}</option>
      {% for option in object_list %}
        <option value="{{ option.id }}">{{ option.name }}</option>
      {% endfor %}
    </select>
    <div class="invalid-feedback">Select a {{ link_name|lower }}</div>
    <button class="btn btn-outline-primary" type="submit">Link {{ link_name|lower }}</button>
  </div>
</form>

src/templates/generic/elements/status.html
{% load static %}
{% load service_custom_tags %}

{% if object.status == 'active' %}
  <span class="badge bg-success">{{ object.status }}</span>
{% endif %}

{% if object.status == 'suspended' %}
  <span class="badge bg-warning text-dark">{{ object.status }}</span>
{% endif %}

{% if object.status == 'terminated' %}
  <span class="badge bg-danger">{{ object.status }}</span>
{% endif %}

{% if object.status == 'deleted' %}
  <span class="badge bg-danger">{{ object.status }}</span>
{% endif %}

{% if object.status == 'decommissioned' %}
  <span class="badge bg-danger">{{ object.status }}</span>
{% endif %}

src/templates/generic/elements/td_action_button.html
{% load service_custom_tags %}
{% setvar request.resolver_match.view_name as view_name %}

{% setvar 'disabled' as update_class_disabled %}
{% setvar 'disabled' as delete_class_disabled %}

{% if view_name == 'contract_list' and perms.service.change_contract %}
{% setvar '' as update_class_disabled %}
{% endif %}

{% if view_name == 'contract_list' and perms.service.delete_contract %}
{% setvar '' as delete_class_disabled %}
{% endif %}


{% if 'hardware' in view_name and perms.hardware.change_hardware %}
{% setvar '' as update_class_disabled %}
{% endif %}

{% if 'hardware' in view_name and perms.hardware.delete_hardware %}
{% setvar '' as delete_class_disabled %}
{% endif %}

{% if 'application' in view_name and perms.service.change_application %}
{% setvar '' as update_class_disabled %}
{% endif %}

{% if 'application' in view_name and perms.service.delete_application %}
{% setvar '' as delete_class_disabled %}
{% endif %}

{% if view_name == 'provider_list' or view_name == 'pricing_list' or view_name == 'service_list' %}
{% if instance_object.owner.id == user.id or instance_object.createdByUserId.id == user.id or user.is_superuser %}
{% setvar '' as update_class_disabled %}
{% setvar '' as delete_class_disabled %}
{% endif %}
{% endif %}

{% if 'contact' in view_name and perms.service.change_contact %}
{% setvar '' as update_class_disabled %}
{% endif %}

{% if 'contact' in view_name and perms.service.delete_contact %}
{% setvar '' as delete_class_disabled %}
{% endif %}

{% if 'company' in view_name and perms.service.change_company %}
{% setvar '' as update_class_disabled %}
{% endif %}

{% if 'company' in view_name and perms.service.delete_company %}
{% setvar '' as delete_class_disabled %}
{% endif %}

<td>
    <div class="btn-group">
    <a class="btn btn-primary btn-sm btn-icon" type="button" href="{% url details_url pk=object.id %}"><i class='bx bx-info-circle'></i></a>

    <button type="button" class="btn btn-sm btn-primary btn-icon dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="visually-hidden">Action</span>
    </button>
    
    <ul class="dropdown-menu">

        {% if object.support_url %}
        <li><a class="dropdown-item" href="{{ object.support_url }}"><i class="bx bx-support"></i> Support</a></li>
        {% endif %}
        <li><a class="dropdown-item {{ update_class_disabled }}" href="{% url update_url pk=object.id %}"><i class="bx bx-pencil"></i> Edit</a></li>
        <li><a class="dropdown-item {{ delete_class_disabled }}" href="{% url delete_url pk=object.id %}"><i class="bx bx-trash-alt"></i> Delete</a></li>


    </ul>

    </div>
</td>