src/core/urls.py
from django.urls import include, path
from service.views.index import IndexView
from service import urls as service_urls
from hardware import urls as hardware_urls
from scim import urls as scim_urls
from restapi import urls as restapi_urls
from gql import urls as gql_urls
from admin import urls as admin_urls
from application import urls as application_urls
from building import urls as building_urls
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import (
    AuthorizationView,
    TokenView,
    RevokeTokenView,
    IntrospectTokenView,
)


# swagger doc: https://appliku.com/post/django-rest-framework-swagger-and-typescript-api-c#swagger-documentation
# and https://pypi.org/project/drf-yasg/#installation

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include(service_urls)),
    path("", include(scim_urls)),
    path("", include(hardware_urls)),
    path("", include(restapi_urls)),
    path("", include(gql_urls)),
    path("", include(admin_urls)),
    path("", include(application_urls)),
    path("", include(building_urls)),
    path("accounts/", include("allauth.urls")),
    path("hc/", include("health_check.urls")),
    path("oauth/authorize/", AuthorizationView.as_view(), name="authorize"),
    path("oauth/token/", TokenView.as_view(), name="token"),
    path("oauth/revoke_token/", RevokeTokenView.as_view(), name="revoke-token"),
    path("oauth/introspect/", IntrospectTokenView.as_view(), name="introspect"),
]

if settings.OIDC_ACTIVATED:
    urlpatterns.append(
        path("oidc/", include("mozilla_django_oidc.urls")),
    )

if not settings.USE_AWS_S3_FOR_FILES:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gql/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from gql.schema import schema

urlpatterns = [
    path("gql/", GraphQLView.as_view(graphiql=True, schema=schema), name="grapheql"),
]

src/service/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from service.manager import UserManager
from django.conf import settings
from service.storages import AWSPrivateMediaStorage
from django.core.files.storage import default_storage
import os
from django.core.mail import send_mail


class Configuration(models.Model):
    CATEGORY = (
        ("public", "Public"),
        ("social_provider", "Social provider"),
        ("private", "private"),
    )
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, blank=True, null=True)
    category = models.CharField(
        max_length=30, choices=CATEGORY, default="private", editable=True
    )
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    enabled = models.BooleanField(default=False, verbose_name=_("Enabled"))

    class Meta:
        verbose_name = _("configuration")
        verbose_name_plural = _("configurations")
        ordering = ["id"]
        permissions = [
            ("export_configuration", "Can export configuration"),
        ]

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_department_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("department")
        verbose_name_plural = _("departments")
        ordering = ["id"]
        permissions = [
            ("export_department", "Can export department"),
        ]

    def __str__(self):
        return self.name


class SubDepartment(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=False,
    )
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_subdepartment_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("sub-department")
        verbose_name_plural = _("sub-departments")
        ordering = ["id"]
        permissions = [
            ("export_subdepartment", "Can export sub-department"),
        ]

    def __str__(self):
        return self.name


class Title(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_title_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("title")
        verbose_name_plural = _("titles")
        ordering = ["id"]
        permissions = [
            ("export_title", "Can export title"),
        ]

    def __str__(self):
        return self.name


class ServiceCategory(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_service_category_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("service category")
        verbose_name_plural = _("service categories")
        ordering = ["id"]
        permissions = [
            ("export_service_catagory", "Can export service catagory"),
        ]

    def __str__(self):
        return self.name


class IdentityProvider(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    icon_url = models.CharField(max_length=255, blank=True, null=True)
    service_url = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_identity_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("identity provider")
        verbose_name_plural = _("identity providers")
        ordering = ["id"]
        permissions = [
            ("export_identity_provider", "Can export identity provider"),
        ]

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_contact_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")
        ordering = ["id"]
        permissions = [
            ("export_contact", "Can export contact"),
        ]

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    currency_preffered = models.CharField(max_length=3, blank=True, null=True)
    contact = models.ManyToManyField(Contact, blank=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("provider")
        verbose_name_plural = _("providers")
        ordering = ["id"]
        permissions = [
            ("export_provider", "Can export provider"),
        ]

    def __str__(self):
        return self.name


class Company(models.Model):
    TRADE_REGISTER = (
        ("public", "Public"),
        ("restricted_access", "Restricted Access"),
        (
            "restricted_access_registry",
            "Restricted Access (business registry except required to requested)",
        ),
    )

    name = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    invoice_email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    brand_name = models.CharField(max_length=255, blank=True, null=True)
    activity = models.CharField(max_length=255, blank=True, null=True)
    incorporation_date = models.DateTimeField(blank=True, null=True)
    share_capital = models.FloatField(blank=True, null=True)
    tax_id = models.CharField(max_length=255, blank=True, null=True)
    trade_register = models.CharField(
        max_length=255, choices=TRADE_REGISTER, editable=True, null=True, blank=True
    )
    shareholders = models.CharField(max_length=255, blank=True, null=True)

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_company_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("company")
        verbose_name_plural = _("companies")
        ordering = ["id"]
        permissions = [
            ("export_company", "Can export company"),
        ]

    def __str__(self):
        return self.name


class ContractDocument(models.Model):
    default_upload_folder = "contract"

    def set_upload_folder(self, folder_name):
        self._upload_folder = folder_name

    def get_upload_folder(self):
        return getattr(self, "_upload_folder", self.default_upload_folder)

    def get_upload_path(instance, filename):
        name, ext = os.path.splitext(filename)
        return os.path.join(instance.get_upload_folder(), str(instance.lpk), name + ext)

    def get_storage():
        storage = default_storage

src/service/views/contact.py
from service.models import Contact, Provider
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    View,
)
from django.urls import reverse_lazy
from core.utils import get_pagination_configuration
from django.shortcuts import get_object_or_404
from django.db.models import Q
from import_export import resources
from core.utils import ViewExport
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect


class ContactListView(LoginRequiredMixin, ListView):
    model = Contact
    template_name = "contact/contacts.html"
    context_object_name = "instance_object"
    extra_context = {
        "custom_title": "Contacts",
        "create_url": "contact_creation",
        "update_url": "contact_update",
        "details_url": "contact_details",
        "delete_url": "contact_delete",
        "export_url": "contact_export",
    }


class ContactSearchView(LoginRequiredMixin, ListView):
    model = Contact
    context_object_name = "instance_object"
    template_name = "contact/contacts.html"
    extra_context = {
        "custom_title": "Contacts",
        "create_url": "contact_creation",
        "update_url": "contact_update",
        "details_url": "contact_details",
        "delete_url": "contact_delete",
        "export_url": "contact_export",
    }

    def get_queryset(self):
        query = self.request.GET.get("query")
        object_list = Contact.objects.filter(
            Q(name__icontains=query)
            | Q(email__icontains=query)
            | Q(firstname__icontains=query)
            | Q(lastname__icontains=query)
            | Q(phone__icontains=query)
        )
        return object_list

    def get_success_url(self):
        return reverse_lazy(
            "provider_list", kwargs={"query": self.request.GET.get("query")}
        )


class ContactDetailView(LoginRequiredMixin, DetailView):
    model = Contact
    context_object_name = "instance_object"
    template_name = "contact/contact.html"
    extra_context = {
        "custom_title": "Contact",
        "update_url": "contact_update",
        "delete_url": "contact_delete",
        "list_url": "contact_list",
    }


class ContactCreateView(LoginRequiredMixin, CreateView):
    model = Contact
    template_name = "contact/create_update_contact.html"
    extra_context = {
        "form_action": "create",
        "custom_title": "contact",
        "list_url": "contact_list",
    }
    context_object_name = "instance_object"
    fields = [
        "name",
        "firstname",
        "lastname",
        "email",
        "phone",
    ]

    def form_valid(self, form):
        form.instance.createdByUserId = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        current_provider = get_object_or_404(Provider, pk=self.kwargs["pk"])
        current_provider.contact.add(self.object.pk)
        path = reverse_lazy("provider_details", kwargs={"pk": current_provider.pk})
        tab = self.request.GET.get("tab", "contact")
        url = f"{path}?tab={tab}"
        return url


class ContactUpdateView(LoginRequiredMixin, UpdateView):
    model = Contact
    template_name = "contact/create_update_contact.html"
    extra_context = {
        "form_action": "update",
        "custom_title": "Contact",
        "list_url": "contact_list",
    }
    context_object_name = "instance_object"
    fields = [
        "name",
        "firstname",
        "lastname",
        "email",
        "phone",
    ]

    def get_success_url(self):
        return reverse_lazy("contact_details", kwargs={"pk": self.object.pk})


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    model = Contact
    template_name = "generic/views/confirm_delete.html"
    extra_context = {"form_action": "delete"}

    def get_success_url(self):
        return reverse_lazy("contact_list")


class RemoveContactLinkToProviderView(View):
    def post(self, request, pk, lpk):
        request.POST.get("relation")
        current_object = get_object_or_404(Provider, pk=pk)
        current_object.contact.remove(lpk)
        path = reverse_lazy("provider_details", kwargs={"pk": current_object.pk})
        tab = self.request.GET.get("tab", "contact")
        url = f"{path}?tab={tab}"
        return HttpResponseRedirect(url)


class ContactResource(resources.ModelResource):
    class Meta:
        model = Contact


class ContactExport(PermissionRequiredMixin, ViewExport):
    filename = "contact.csv"
    content_type = "csv"
    resource = ContactResource
    permission_required = "service.export_contact"

src/templates/contact/contact.html
{% extends "generic/views/details_view/details_view.html" %}

{% load static %}
{% load service_custom_tags %}

{% block nav_menue %}
{% include 'generic/views/details_view/elements/li_tab_core.html' with tab_name='main' tab_active_value='active' %}
{% endblock nav_menue %}


{% block nav_content %}

<!-- tab -->
<div class="tab-pane fade show active" id="navs-pills-top-main" role="tabpanel">
  <div class="card mb-4">
    <h5 class="card-header">Main</h5>
    <div class="card-body">
      <div class="row">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>Name</td>
              <td>{{ instance_object.name }}</td>
            </tr>
            <tr>
              <td>Firstname</td>
              <td>{{ instance_object.firstname }}</td>
            </tr>
            <tr>
              <td>Lastname</td>
              <td>{{ instance_object.lastname }}</td>
            </tr>
            <tr>
              <td>Email</td>
              <td>{{ instance_object.email }}</td>
            </tr>
            <tr>
              <td>Phone</td>
              <td>{{ instance_object.phone }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% include 'generic/views/details_view/elements/button_update.html' with placeholder_edit_url=update_url%}
</div>
{% endblock nav_content %}

src/templates/contact/contacts.html
{% extends 'generic/views/list_view/list_view.html' %}
{% block table_header %}
  <tr>
    <th scope="col">Action</th>
    <th scope="col">Name</th>
    <th scope="col">Firstname</th>
    <th scope="col">Lastname</th>
    <th scope="col">Email</th>
    <th scope="col">Phone</th>
  </tr>
{% endblock %}
{% block table_body %}
  {% for object in instance_object %}
    <tr>
      {% include 'generic/elements/td_action_button.html' %}
      <td>{{ object.name }}</td>
      <td>{{ object.firstname }}</td>
      <td>{{ object.lastname }}</td>
      <td>{{ object.email }}</td>
      <td>{{ object.phone }}</td>
    </tr>
  {% endfor %}
{% endblock %}

src/templates/contact/create_update_contact.html
{% extends "generic/views/create_update/create_update_view.html" %}
{% block form_field %}

<!-- Basic Layout -->
<div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Mandatory information</h5>
        <small class="text-muted float-end">{{ custom_title|capfirst }}</small>
      </div>
      <div class="card-body">

                <div class="row mb-3">
                    <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_name">Contact Name</label>
                  <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="id_name" required maxlength="255"
                            placeholder="255 charts max" value="{{ instance_object.name }}">
                        <div class="invalid-feedback">
                            Name is required.
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
            

<!-- Basic Layout -->
<div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Optional informations</h5>
        <small class="text-muted float-end">{{ custom_title|capfirst }}</small>
      </div>
      <div class="card-body">


                            <div class="row mb-3">
                                <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_firstname">Firstname</label>
                                <div class="col-sm-10">
                                    <input type="text" name="firstname" class="form-control" id="id_firstname" maxlength="255"
                                        placeholder="" value="{{ instance_object.firstname }}">
                                    <div class="invalid-feedback">
                                        Indicated an firstname
                                    </div>
                                </div>
                            </div>


                            <div class="row mb-3">
                                <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_lastname">Lastname</label>
                                <div class="col-sm-10">
                                        <input type="text" name="lastname" class="form-control" id="id_lastname" maxlength="255"
                                            placeholder="" value="{{ instance_object.lastname }}">
                                        <div class="invalid-feedback">
                                            Indicated a lastname
                                        </div>
                                    </div>
                                </div>


                                    <div class="row mb-3">
                                <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_email">Contact email</label>
                                <div class="col-sm-10">

                                    {% if instance_object.email != blank %}
                                    <input type="email" name="email" class="form-control" id="id_email" maxlength="255"
                                                placeholder="" value="{{ instance_object.email }}">
                                    {% else %}
                                    <input type="email" name="email" class="form-control" id="id_email" maxlength="255"
                                                placeholder="" value="">
                                    
                                    {% endif %}
                                            
                                            <div class="invalid-feedback">
                                                Indicated an email address.
                                            </div>
                                        </div>
                                    </div>
                                        <div class="row mb-3">
                                            <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_phone">Phone number</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="phone" class="form-control" id="id_phone" maxlength="255"
                                                    placeholder="+34 689 67 68 99" value="{{ instance_object.phone }}">
                                                <div class="invalid-feedback">
                                                    Indicated a phone number
                                                </div>
                                            </div>   
                                        </div> 
                                        {% include 'generic/views/create_update/elements/create_update_submit_button.html' %}   
                                    </div> 
                                </div> 
                            </div>                    
{% endblock %}