src/core/urls.py
from django.urls import include, path
from service.views.index import IndexView
from service import urls as service_urls
from hardware import urls as hardware_urls
from scim import urls as scim_urls
from restapi import urls as restapi_urls
from gql import urls as gql_urls
from admin import urls as admin_urls
from application import urls as application_urls
from building import urls as building_urls
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import (
    AuthorizationView,
    TokenView,
    RevokeTokenView,
    IntrospectTokenView,
)


# swagger doc: https://appliku.com/post/django-rest-framework-swagger-and-typescript-api-c#swagger-documentation
# and https://pypi.org/project/drf-yasg/#installation

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include(service_urls)),
    path("", include(scim_urls)),
    path("", include(hardware_urls)),
    path("", include(restapi_urls)),
    path("", include(gql_urls)),
    path("", include(admin_urls)),
    path("", include(application_urls)),
    path("", include(building_urls)),
    path("accounts/", include("allauth.urls")),
    path("hc/", include("health_check.urls")),
    path("oauth/authorize/", AuthorizationView.as_view(), name="authorize"),
    path("oauth/token/", TokenView.as_view(), name="token"),
    path("oauth/revoke_token/", RevokeTokenView.as_view(), name="revoke-token"),
    path("oauth/introspect/", IntrospectTokenView.as_view(), name="introspect"),
]

if settings.OIDC_ACTIVATED:
    urlpatterns.append(
        path("oidc/", include("mozilla_django_oidc.urls")),
    )

if not settings.USE_AWS_S3_FOR_FILES:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gql/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from gql.schema import schema

urlpatterns = [
    path("gql/", GraphQLView.as_view(graphiql=True, schema=schema), name="grapheql"),
]

src/service/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from service.manager import UserManager
from django.conf import settings
from service.storages import AWSPrivateMediaStorage
from django.core.files.storage import default_storage
import os
from django.core.mail import send_mail


class Configuration(models.Model):
    CATEGORY = (
        ("public", "Public"),
        ("social_provider", "Social provider"),
        ("private", "private"),
    )
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, blank=True, null=True)
    category = models.CharField(
        max_length=30, choices=CATEGORY, default="private", editable=True
    )
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    enabled = models.BooleanField(default=False, verbose_name=_("Enabled"))

    class Meta:
        verbose_name = _("configuration")
        verbose_name_plural = _("configurations")
        ordering = ["id"]
        permissions = [
            ("export_configuration", "Can export configuration"),
        ]

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_department_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("department")
        verbose_name_plural = _("departments")
        ordering = ["id"]
        permissions = [
            ("export_department", "Can export department"),
        ]

    def __str__(self):
        return self.name


class SubDepartment(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=False,
    )
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_subdepartment_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("sub-department")
        verbose_name_plural = _("sub-departments")
        ordering = ["id"]
        permissions = [
            ("export_subdepartment", "Can export sub-department"),
        ]

    def __str__(self):
        return self.name


class Title(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_title_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("title")
        verbose_name_plural = _("titles")
        ordering = ["id"]
        permissions = [
            ("export_title", "Can export title"),
        ]

    def __str__(self):
        return self.name


class ServiceCategory(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_service_category_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("service category")
        verbose_name_plural = _("service categories")
        ordering = ["id"]
        permissions = [
            ("export_service_catagory", "Can export service catagory"),
        ]

    def __str__(self):
        return self.name


class IdentityProvider(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    icon_url = models.CharField(max_length=255, blank=True, null=True)
    service_url = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_identity_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("identity provider")
        verbose_name_plural = _("identity providers")
        ordering = ["id"]
        permissions = [
            ("export_identity_provider", "Can export identity provider"),
        ]

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_contact_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")
        ordering = ["id"]
        permissions = [
            ("export_contact", "Can export contact"),
        ]

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    currency_preffered = models.CharField(max_length=3, blank=True, null=True)
    contact = models.ManyToManyField(Contact, blank=True)
    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        auto_created=True,
        related_name="FK_provider_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("provider")
        verbose_name_plural = _("providers")
        ordering = ["id"]
        permissions = [
            ("export_provider", "Can export provider"),
        ]

    def __str__(self):
        return self.name


class Company(models.Model):
    TRADE_REGISTER = (
        ("public", "Public"),
        ("restricted_access", "Restricted Access"),
        (
            "restricted_access_registry",
            "Restricted Access (business registry except required to requested)",
        ),
    )

    name = models.CharField(max_length=255, blank=True, null=True)
    vat_number = models.CharField(max_length=255, blank=True, null=True)
    invoice_email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    street_number = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    brand_name = models.CharField(max_length=255, blank=True, null=True)
    activity = models.CharField(max_length=255, blank=True, null=True)
    incorporation_date = models.DateTimeField(blank=True, null=True)
    share_capital = models.FloatField(blank=True, null=True)
    tax_id = models.CharField(max_length=255, blank=True, null=True)
    trade_register = models.CharField(
        max_length=255, choices=TRADE_REGISTER, editable=True, null=True, blank=True
    )
    shareholders = models.CharField(max_length=255, blank=True, null=True)

    createdByUserId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        auto_created=True,
        related_name="FK_company_created_by_user_id",
    )
    creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    class Meta:
        verbose_name = _("company")
        verbose_name_plural = _("companies")
        ordering = ["id"]
        permissions = [
            ("export_company", "Can export company"),
        ]

    def __str__(self):
        return self.name


class ContractDocument(models.Model):
    default_upload_folder = "contract"

    def set_upload_folder(self, folder_name):
        self._upload_folder = folder_name

    def get_upload_folder(self):
        return getattr(self, "_upload_folder", self.default_upload_folder)

    def get_upload_path(instance, filename):
        name, ext = os.path.splitext(filename)
        return os.path.join(instance.get_upload_folder(), str(instance.lpk), name + ext)

    def get_storage():
        storage = default_storage

src/service/views/company.py
from service.models import Company
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.db.models import Q
from import_export import resources
from core.utils import ViewExport


class CompanyListView(LoginRequiredMixin, ListView):
    model = Company
    template_name = "company/companies.html"
    context_object_name = "instance_object"
    extra_context = {
        "custom_title": "Companies",
        "create_url": "company_creation",
        "update_url": "company_update",
        "details_url": "company_details",
        "delete_url": "company_delete",
        "export_url": "company_export",
    }


class CompanySearchView(LoginRequiredMixin, ListView):
    model = Company
    context_object_name = "instance_object"
    template_name = "company/companies.html"
    extra_context = {
        "custom_title": "Companies",
        "create_url": "company_creation",
        "update_url": "company_update",
        "details_url": "company_details",
        "delete_url": "company_delete",
        "export_url": "company_export",
    }

    def get_queryset(self):
        query = self.request.GET.get("query")
        object_list = Company.objects.filter(
            Q(name__icontains=query)
            | Q(invoice_email__icontains=query)
            | Q(vat_number__icontains=query)
            | Q(address__icontains=query)
            | Q(country__icontains=query)
            | Q(city__icontains=query)
        )
        return object_list

    def get_success_url(self):
        return reverse_lazy(
            "company_list", kwargs={"query": self.request.GET.get("query")}
        )


class CompanyDetailView(LoginRequiredMixin, DetailView):
    model = Company
    context_object_name = "instance_object"
    template_name = "company/company.html"
    extra_context = {
        "custom_title": "Company",
        "update_url": "company_update",
        "delete_url": "company_delete",
        "list_url": "company_list",
    }

    def get_success_url(self):
        tab = self.request.GET.get("tab")
        path = reverse_lazy("company_details", kwargs={"pk": self.object.pk})
        tab = self.request.GET.get("tab", "main")
        url = f"{path}?tab={tab}"
        return url


class CompanyCreateView(PermissionRequiredMixin, CreateView):
    model = Company
    template_name = "company/create_update_company.html"
    permission_required = "service.add_company"
    extra_context = {
        "form_action": "create",
        "custom_title": "Company",
        "list_url": "company_list",
    }
    context_object_name = "instance_object"
    fields = [
        "name",
        "vat_number",
        "invoice_email",
        "address",
        "street_number",
        "city",
        "zip_code",
        "country",
        "brand_name",
        "activity",
        "incorporation_date",
        "share_capital",
        "tax_id",
        "trade_register",
        "shareholders",
    ]

    def form_valid(self, form):
        form.instance.createdByUserId = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("company_details", kwargs={"pk": self.object.pk})


class CompanyUpdateView(PermissionRequiredMixin, UpdateView):
    model = Company
    permission_required = "service.change_company"
    template_name = "company/create_update_company.html"
    extra_context = {
        "form_action": "update",
        "custom_title": "Company",
        "list_url": "company_list",
    }
    context_object_name = "instance_object"
    fields = [
        "vat_number",
        "invoice_email",
        "address",
        "street_number",
        "city",
        "zip_code",
        "country",
        "brand_name",
        "activity",
        "incorporation_date",
        "share_capital",
        "tax_id",
        "trade_register",
        "shareholders",
    ]

    def get_success_url(self):
        return reverse_lazy("company_details", kwargs={"pk": self.object.pk})


class CompanyDeleteView(PermissionRequiredMixin, DeleteView):
    model = Company
    template_name = "generic/views/confirm_delete.html"
    extra_context = {"form_action": "delete"}
    permission_required = "service.delete_company"

    def get_success_url(self):
        return reverse_lazy("company_list")


class CompanyResource(resources.ModelResource):
    class Meta:
        model = Company


class CompanyExport(PermissionRequiredMixin, ViewExport):
    filename = "company.csv"
    content_type = "csv"
    resource = CompanyResource
    permission_required = "service.export_company"

src/templates/company/companies.html
{% extends 'generic/views/list_view/list_view.html' %}
{% block table_header %}
  <tr>
    <th scope="col">Action</th>
    <th scope="col">Name</th>
    <th scope="col">Invoice email</th>
    <th scope="col">VAT Number</th>
    <th scope="col">Address</th>
  </tr>
{% endblock %}
{% block table_body %}
  {% for object in instance_object %}
    <tr>
      {% include 'generic/elements/td_action_button.html' %}
      <td>{{ object.name }}</td>
      <td>{{ object.invoice_email }}</td>
      <td>{{ object.vat_number }}</td>
      <td>
        {{ object.address }} {{ object.street_number }}<br />{{ object.zip_code }}<br />{{ object.city }}<br />{{ object.country }}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

src/templates/company/company.html
{% extends "generic/views/details_view/details_view.html" %}
{% load static %}
{% load service_custom_tags %}


{% block nav_menue %}

{% setvar 'show active' as m_tab_active_value %}


{% include 'generic/views/details_view/elements/li_tab_core.html' with tab_name='main' tab_active_value=m_tab_active_value %}

{% endblock nav_menue %}




{% block nav_content %}

{% setvar 'show active' as m_tab_active_value %}



{% include 'company/elements/nav_main.html' with tab_active_value=m_tab_active_value %}


{% endblock nav_content %}

src/templates/company/create_update_company.html
{% extends 'generic/views/create_update/create_update_view.html' %}
{% block form_field %}
  {% load humanize %}
  <!-- Basic Layout -->
  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Mandatory information</h5>
        <small class="text-muted float-end">{{ custom_title|capfirst }}</small>
      </div>

      <div class="card-body">
        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_name">Name</label>
          <div class="col-sm-10">
            <input type="text" name="name" class="form-control" id="id_name" required maxlength="255" placeholder="255 charts max" value="{{ instance_object.name }}" />
            <div class="invalid-feedback">Name is required.</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Optional informations</h5>
        <small class="text-muted float-end">{{ custom_title|capfirst }}</small>
      </div>

      <div class="card-body">
        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_invoice_email">Invoice email</label>
          <div class="col-sm-10">
            <input type="email" name="invoice_email" class="form-control" id="id_invoice_email" maxlength="255" placeholder="" value="{{ instance_object.invoice_email }}" />
            <div class="invalid-feedback">Indicated an invoice email address.</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_vat_number">VAT number</label>
          <div class="col-sm-10">
            <input type="text" name="vat_number" class="form-control" id="id_vat_number" maxlength="255" placeholder="" value="{{ instance_object.vat_number }}" />
            <div class="invalid-feedback">Indicated a VAT number</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_address">Address</label>
          <div class="col-sm-10">
            <input type="text" name="address" class="form-control" id="id_address" maxlength="255" placeholder="" value="{{ instance_object.address }}" />
            <div class="invalid-feedback">Indicated an address</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_street_number">Street number</label>
          <div class="col-sm-10">
            <input type="text" name="street_number" class="form-control" id="id_street_number" maxlength="255" placeholder="" value="{{ instance_object.street_number }}" />
            <div class="invalid-feedback">Indicated a street number</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_zip_code">ZIP code</label>
          <div class="col-sm-10">
            <input type="text" name="zip_code" class="form-control" id="id_zip_code" maxlength="255" placeholder="" value="{{ instance_object.zip_code }}" />
            <div class="invalid-feedback">Indicated a zip_code</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_city">City</label>
          <div class="col-sm-10">
            <input type="text" name="city" class="form-control" id="id_city" maxlength="255" placeholder="" value="{{ instance_object.city }}" />
            <div class="invalid-feedback">Indicated a city</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_country">Country</label>
          <div class="col-sm-10">
            <input type="text" name="country" class="form-control" id="id_country" maxlength="255" placeholder="" value="{{ instance_object.country }}" />
            <div class="invalid-feedback">Indicated a country</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_country">Brand name</label>
          <div class="col-sm-10">
            <input type="text" name="brand_name" class="form-control" id="id_brand_name" maxlength="255" placeholder="" value="{{ instance_object.brand_name }}" />
            <div class="invalid-feedback">Indicated a brand name</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_activity">Activity</label>
          <div class="col-sm-10">
            <input type="text" name="activity" class="form-control" id="id_activity" maxlength="255" placeholder="" value="{{ instance_object.activity }}" />
            <div class="invalid-feedback">Indicated an activity</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_incorporation_date">incorporation_date</label>
          <div class="col-sm-10">
            <input type="date" name="incorporation_date" class="form-control" id="id_incorporation_date" value="{{ instance_object.incorporation_date|date:'d/m/Y' }}" />
            <div class="invalid-feedback">Indicated a date</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_share_capital">Share capital</label>
          <div class="col-sm-10">
            <input type="number" name="share_capital" class="form-control" id="id_share_capital" placeholder="" value="{{ instance_object.share_capital }}" />
            <div class="invalid-feedback">Indicated a number</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_tax_id">Tax ID</label>
          <div class="col-sm-10">
            <input type="text" name="tax_id" class="form-control" id="id_tax_id" maxlength="255" placeholder="" value="{{ instance_object.tax_id }}" />
            <div class="invalid-feedback">Indicated a tax ID</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_trade_register">trade_register</label>
          <div class="col-sm-10">
            <select required class="select tom-select" id="id_trade_register" name="trade_register">
              {% for option in form.trade_register %}
                {{ option }}
              {% endfor %}
            </select>
            <div class="invalid-feedback">Indicated a trade register</div>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-col-sm-2 col-form-label" for="id_shareholders">Shareholders</label>
          <div class="col-sm-10">
            <input type="text" name="shareholders" class="form-control" id="id_shareholders" maxlength="255" placeholder="" value="{{ instance_object.shareholders }}" />
            <div class="invalid-feedback">Indicated a shareholders</div>
          </div>
        </div>

        {% include 'generic/views/create_update/elements/create_update_submit_button.html' %}
      </div>
    </div>
  </div>
{% endblock %}